#!/usr/bin/env bash
# This program should generate a job script from input

echo -n "Enter the output file name: "
read name
echo -n "Enter input file name: "
read input
first=$(egrep "0 0 0" $input.xsc | cut -f 1 -s -d ' ')
#echo -n "Enter first timestep: "
#read first
echo "Starting at step $first"
echo -n "Enter run time (in ns): "
read ns
if [ $ns="end" ]; then
    echo -n "Enter the end time (in ns):"
    read last
    steps=$(($last-$first))
fi
if [ -z "$ns" ]; then
    echo -n "Enter run time (in steps):"
    read steps
fi
echo -n "Enter your wall time in whole hours (if known): "
read walltime
if [ -z "$steps" ]; then
     steps=$(($ns*500000))
fi

if [ -z "$walltime" ]; then
     walltime=$(($steps*50/10000000))
fi

echo "#!/bin/bash" | cat > $name.job
echo "#SBATCH -t $walltime:00:00" | cat >> $name.job
cat ~/bin/gputemplate >> $name.job
echo "\$BINDIR/namd2 +idlepoll +p \$SLURM_NPROCS +pemap 0-13+14 $name.inp>& $name.log" | cat >> $name.job
echo "transfer $name" | cat >> $name.job

cat ~/bin/inptemplate1 > $name.inp
echo "outputname        $name;" | cat >> $name.inp
echo "set inputname    $input;" | cat >> $name.inp
echo "firsttimestep   $first;" | cat >> $name.inp
cat ~/bin/inptemplate2 >> $name.inp
echo "# run" | cat >> $name.inp
total=$(($steps+$first))
echo "numsteps          $total;" | cat >>$name.inp
echo "run               $steps;" | cat >> $name.inp

echo "Setting walltime as $walltime hours"
